---
title: "midterm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
# Set up:
```{r, message=FALSE}
library(tidyverse)
library(drat)
library(ggplot2)
library(maps)
library(dplyr)
library(gridExtra)
library(magrittr)
library(viridis)
library(lubridate)
```




```{r, message=FALSE}
public<-read.csv("PublicAssistanceFundedProjectsDetails.csv",header = TRUE)

```

```{r}
# public$county<-tolower(public$county)
# public$state<-tolower(public$state)
# public<-rename(public,region = state)
# public<-rename(public,subregion = county)
public[which(public$stateNumberCode<10),"stateNumberCode"]<-paste(0,as.character(public[which(public$stateNumberCode<10),"stateNumberCode"]),sep="")
public$stateNumberCode%<>%as.character()

```



```{r}

public$countyCode%<>%as.numeric()
temp1<-paste('00',as.character(public[which(public$countyCode<10),"countyCode"]),sep="")
temp2<-paste('0',as.character(public[which(public$countyCode<100&public$countyCode>9),"countyCode"]),sep="")

public[which(public$countyCode<100&public$countyCode>9),"countyCode"]<-temp2
public[which(as.numeric(public$countyCode)<10),"countyCode"]<-temp1
public$countyCode%<>%as.character()
public['fips']<-paste(public$stateNumberCode,public$countyCode,sep="")
public%<>%select(c("disasterNumber","declarationDate","incidentType","county","state","fips"))
public<-public[!duplicated(public),]
```

```{r}
save<-public
save%<>%na.omit()
write.csv(save,file="save.csv",col.names=TRUE)
```


```{r}
public<-save
#counties_df<-us_map(regions="counties")
county_fips <- county.fips
county_fips$fips <- str_pad(county_fips$fips,5,side = "left",pad = "0")
map_county <- map_data("county")
map_states_border<-map_data("state")
```

```{r}

# Add the longitude and latitude information
public%<>%na.omit()
public<-merge(public, county_fips,by = c("fips"))%>%separate(polyname, sep = ",", into = c("region","subregion"))
public <-merge(public,map_county, by=c("region","subregion"))
public%<>%na.omit()
# Use lubridate to tidy up the declaration time
public$declarationDate%<>%ymd_hms()
#public%<>%subset(year(public$declarationDate)>2009)
public%<>%select(-c("county","state"))
public["yy"]<-year(public$declarationDate)
public["mm"]<-month(public$declarationDate)
public["dd"]<-day(public$declarationDate)

```
```{r}
write.csv(public,file="public.csv",col.names=TRUE)
```
